---
title: "Data poor validation" 
subtitle: "Myers data"
author: "Laurence Kell"
output: rmarkdown:::word_document
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEncoding{UTF-8}
tags: FLPKG FLR
license: Creative Commons Attribution-ShareAlike 4.0 International
---
  
```{r knitr_init, echo=FALSE, results="hide"}
library(knitr)
## Global options
opts_chunk$set(echo    =FALSE,
               eval    =TRUE,
               cache   =TRUE,
               cache.path="../cache/myers/",
               prompt  =FALSE,
               comment =NA,
               message =FALSE,
               tidy    =FALSE,
               warning =FALSE,
               fig.height=6,
               fig.width =6,
               fig.path  ="../tex/myers-",
               dev       ="png")

options(digits=3)

iFig=0
```

```{r, pkgs, echo=FALSE, message=FALSE}
library(reshape)
library(plyr)
library(dplyr)
library(ggplot2)

library(r4ss)
library(GGally)

library(mydas)

library(sraplus)

source('~/Desktop/flr/xvl/R/ss-prd.R', echo=FALSE)
```

```{r, data, fig.height=6, fig.width=6}
spp=c("Thunnus obesus",
      "Kajikia albida",
      "Xiphias gladius",
      "Makaira nigricans",
      "Thunnus albacares")
names(spp)=c("bet","bum","swo","whm","yft")

fls=data.frame(
  file=c("/home/laurence-kell/Desktop/rfmo/iccat/sc-eco/iccat/ss/bet/2018/_BET_2018_refV2.dat",
         "/home/laurence-kell/Desktop/rfmo/iccat/sc-eco/iccat/ss/bum/2018/_BUM.dat.ss",
         "/home/laurence-kell/Desktop/rfmo/iccat/sc-eco/iccat/ss/sma/2019/run1/data.ss",
         "/home/laurence-kell/Desktop/rfmo/iccat/sc-eco/iccat/ss/swon/2017/run1/_SWO_DATA.dat",
         "/home/laurence-kell/Desktop/rfmo/iccat/sc-eco/iccat/ss/whm/2019/run6/_whm.dat",
         "/home/laurence-kell/Desktop/rfmo/iccat/sc-eco/iccat/ss/whm/2019/run7/_whm.dat",
         "/home/laurence-kell/Desktop/rfmo/iccat/sc-eco/iccat/ss/yft/2019/run1/YFTdata.7.13.19CAL_AK.dat",
         "/home/laurence-kell/Desktop/papers/pErr/inputs/iccat-yft/base/YFTdata.7.13.19CAL_AK.dat")[-c(3,6,7)],
  stk=c("bet", "bum", "sma", "swo", "whm", "whm", "yft", "yft")[-c(3,6,7)],
  run=c("base","base","base","base","run6","run7","base","windows")[-c(3,6,7)],
  stringsAsFactors=FALSE)

base =dlply(fls, .(file), with, {
  print(file); SS_output(dirname(file),ncols=250,forecast=FALSE,verbose=FALSE,warn=FALSE,
                         hidewarn=FALSE,printstats=FALSE,covar=FALSE)})

rfpts=cbind(ldply(base, function(x) getRf(x)[1,-1]),fls[,-1])
kobe =merge(ldply(base,function(x) x$Kobe)[,-5],rfpts,by="file")
sp   =merge(ldply(base,spFunc),fls,by="file")
nseas=ldply(base, function(x) data.frame(nseas=length(unique(x$timeseries$Seas))))
sp   =merge(sp,nseas,by="file")   
sp$biomass=sp$biomass/sp$nseas

pt=transmute(rfpts,
               stk  =stk,
               shape=ssbmsy/ssb0,
               k    =ssb0,
               msy  =msy,
               bmsy =ssbmsy)
pt=adply(pt,1,function(x) data.frame(p=optimise(function(x,y) (y-(1/(1+x))^(1/x))^2,c(-0.9999,10),y=x$shape)$minimum))
pt=transform(pt,r=(1+p)*(msy/bmsy))
ss=merge(sp,pt)
```

```{r, bd, eval=FALSE}
bd=dlply(ss, .(stk), function(x){

  cdp<-try(sraplus::format_driors(
    use_heuristics=!TRUE,
    taxa          =spp[x$stk[1]],
    
    index      = x$ssb,
    index_year = x$year,
    catch      = x$catch,
    years      = x$year
    ))
  
  fit<-try(sraplus::fit_sraplus(
    driors = cdp,      
    engine = "tmb",
    model  = "sraplus_tmb",
    estimate_qslope = FALSE,
    estimate_proc_error = TRUE))

  if ("try-error"%in%is(fit)) return(NULL)
  
  fit})

save(bd,file="/home/laurence-kell/Desktop/papers/data-poor/results/ssBDResults.RData")
```


```{r, bd10, eval=!FALSE}
bd10=dlply(ss, .(stk), function(x){
  
  x=subset(x,year>=max(year)-9)
  
  cdp<-try(sraplus::format_driors(
    use_heuristics=!TRUE,
    taxa          =spp[x$stk[1]],
    
    index      = x$ssb,
    index_year = x$year,
    catch      = x$catch,
    years      = x$year
    ))
  
  fit<-try(sraplus::fit_sraplus(
    driors = cdp,      
    engine = "tmb",
    model  = "sraplus_tmb",
    estimate_qslope = FALSE,
    estimate_proc_error = TRUE))

  if ("try-error"%in%is(fit)) return(NULL)
  
  fit})

save(bd10,file="/home/laurence-kell/Desktop/papers/data-poor/results/ssBD10Results.RData")
```


```{r, bd4, eval=!FALSE}
bd4=dlply(ss, .(stk), function(x){

  set.seed(1234)
  
  cdp<-try(sraplus::format_driors(
    use_heuristics=!TRUE,
    taxa          =spp[x$stk[1]],
    index      = x$ssb*rev(rlnorm(length(index),0,0.4)),
    index_year = x$year,
    catch      = x$catch,
    years      = x$year
    ))
  
  fit<-try(sraplus::fit_sraplus(
    driors = cdp,      
    engine = "tmb",
    model  = "sraplus_tmb",
    estimate_qslope = FALSE,
    estimate_proc_error = TRUE))

  if ("try-error"%in%is(fit)) return(NULL)
  
  fit})

save(bd4,file="/home/laurence-kell/Desktop/papers/data-poor/results/ssBD4Results.RData")
```


```{r, bd410, eval=!FALSE}
bd410=dlply(ss, .(stk), function(x){

  x=subset(x,year>=max(year)-9)

  set.seed(1234)
  
  cdp<-try(sraplus::format_driors(
    use_heuristics=!TRUE,
    taxa          =spp[x$stk[1]],
    index      = x$ssb*rev(rlnorm(length(index),0,0.4)),
    index_year = x$year,
    catch      = x$catch,
    years      = x$year
    ))
  
  fit<-try(sraplus::fit_sraplus(
    driors = cdp,      
    engine = "tmb",
    model  = "sraplus_tmb",
    estimate_qslope = FALSE,
    estimate_proc_error = TRUE))

  if ("try-error"%in%is(fit)) return(NULL)
  
  fit})

save(bd410,file="/home/laurence-kell/Desktop/papers/data-poor/results/ssBD410Results.RData")
```

```{r, sra, eval=FALSE}
sra=dlply(ss, .(stk), function(x){
  
  cdp<-try(sraplus::format_driors(
    use_heuristics=TRUE,
    taxa          =spp[x$stk[1]],
    
    catch      = x$catch,
    years      = x$year
  ))
  
  
  fit<-try(sraplus::fit_sraplus(
    driors = cdp,
    engine = "sir",
    adapt_delta = 0.9,
    max_treedepth = 10,
    n_keep = 4000,
    chains = 1,
    cores = 1,
    estimate_qslope = FALSE,
    estimate_proc_error = TRUE))
  
  if ("try-error"%in%is(fit)) return(NULL)
  
  fit})

save(sra,file="/home/laurence-kell/Desktop/papers/data-poor/results/ssSRAResults.RData")
```


```{r, sra10, eval=!FALSE}
sra10=dlply(ss, .(stk), function(x){
  
  x=subset(x,year>=max(year)-9)

  cdp<-try(sraplus::format_driors(
    use_heuristics=TRUE,
    taxa          =spp[x$stk[1]],
    
    catch      = x$catch,
    years      = x$year
  ))
  
  
  fit<-try(sraplus::fit_sraplus(
    driors = cdp,
    engine = "sir",
    adapt_delta = 0.9,
    max_treedepth = 10,
    n_keep = 4000,
    chains = 1,
    cores = 1,
    estimate_qslope = FALSE,
    estimate_proc_error = TRUE))
  
  if ("try-error"%in%is(fit)) return(NULL)
  
  fit})

save(sra10,file="/home/laurence-kell/Desktop/papers/data-poor/results/ssSRA10Results.RData")
```


```{r, srap, eval=FALSE}
srap=dlply(ss, .(stk), function(x){

  r=x$r[1]
  k=x$k[1]
  p=x$p[1]
  
  cdp<-try(sraplus::format_driors(
    use_heuristics=!TRUE,
    taxa          =spp[x$stk[1]],
    catch         =x$catch,
    years         =x$year,
    
    shape_prior       =p+1,
    growth_rate_prior =r,
    k_prior           =k,
    initial_state     =0.75, #x$timeseries$ssb[1]/x$refpts[1,"k"],
    terminal_state    =0.2, #x$timeseries$ssb[length(x$timeseries$ssb)]/x$refpts[1,"k"],

    k_prior_cv          =0.3,
    growth_rate_prior_cv=0.3,
    shape_prior_cv      =0.3,
    initial_state_cv    =0.3,
    terminal_state_cv   =0.5
  ))
  
  fit<-try(sraplus::fit_sraplus(
    driors = cdp,
    engine = "sir",
    adapt_delta = 0.9,
    max_treedepth = 10,
    n_keep = 4000,
    chains = 1,
    cores = 1,
    estimate_qslope = FALSE,
    estimate_proc_error = TRUE))
  
  if ("try-error"%in%is(fit)) return(NULL)
  
  fit})

save(srap,file="/home/laurence-kell/Desktop/papers/data-poor/results/ssSRPResults.RData")
```


```{r, srap10, eval=!FALSE}
srap10=dlply(ss, .(stk), function(x){

  x=subset(x,year>=max(year)-9)

  r=x$r[1]
  k=x$k[1]
  p=x$p[1]
  
  cdp<-try(sraplus::format_driors(
    use_heuristics=!TRUE,
    taxa          =spp[x$stk[1]],
    catch         =x$catch,
    years         =x$year,
    
    shape_prior       =p+1,
    growth_rate_prior =r,
    k_prior           =k,
    initial_state     =0.75, #x$timeseries$ssb[1]/x$refpts[1,"k"],
    terminal_state    =0.2, #x$timeseries$ssb[length(x$timeseries$ssb)]/x$refpts[1,"k"],

    k_prior_cv          =0.3,
    growth_rate_prior_cv=0.3,
    shape_prior_cv      =0.3,
    initial_state_cv    =0.3,
    terminal_state_cv   =0.5
  ))
  
  fit<-try(sraplus::fit_sraplus(
    driors = cdp,
    engine = "sir",
    adapt_delta = 0.9,
    max_treedepth = 10,
    n_keep = 4000,
    chains = 1,
    cores = 1,
    estimate_qslope = FALSE,
    estimate_proc_error = TRUE))
  
  if ("try-error"%in%is(fit)) return(NULL)
  
  fit})

save(srap10,file="/home/laurence-kell/Desktop/papers/data-poor/results/ssSRP10Results.RData")
```


```{r, cmsy, eval=!FALSE}
library(fishmethods)
source('~/Desktop/flr/fishmethods/R/catchmsy.R', echo=TRUE)

cmsy=bds=dlply(ss, .(stk), function(x){

  r=x$r[1]
  k=x$k[1]
  
  catch = x$catch
  year  = x$year

  fit<-catchmsy(
      year   =year,
      catch  =catch,
      catchCV=NULL,
      catargs=list(dist="none",low=0,up=Inf,unit="MT"),
      l0=list(low=0.75, #max(1,min(x$timeseries$ssb[1]/x$refpts[1,"k"],1),
              up =0.75, #min(x$timeseries$ssb[1]/x$refpts[1,"k"],1),
              step=0),
      lt=list(low  =0.1, #rev(x$timeseries$ssb)[1]/x$refpts[1,"k"]*0.5,
              up   =0.8, #rev(x$timeseries$ssb)[1]/x$refpts[1,"k"]*2.0,
              refyr=max(x$year)),sigv=0,
      k=list(dist="unif",low=k*.1,up=k*10,mean=0,sd=0),
      r=list(dist="unif",low=r*.2,up=r*2,mean=0,sd=0),
      M=list(dist="unif",low=0.2,up=0.2,mean=0.00,sd=0.00),
      nsims=30000,
      graphs=NULL)

  fit})

save(cmsy,file="/home/laurence-kell/Desktop/papers/data-poor/results/ssCMSYResults.RData")
```


```{r, cmsy10, eval=!FALSE}
library(fishmethods)
source('~/Desktop/flr/fishmethods/R/catchmsy.R', echo=TRUE)

cmsy10=dlply(ss, .(stk), function(x){
  
  x=subset(x,year>=max(year)-9)

  r=x$r[1]
  k=x$k[1]
  
  catch = x$catch
  year  = x$year

  fit<-catchmsy(
      year   =year,
      catch  =catch,
      catchCV=NULL,
      catargs=list(dist="none",low=0,up=Inf,unit="MT"),
      l0=list(low=0.8, #max(1,min(x$timeseries$ssb[1]/x$refpts[1,"k"],1),
              up =0.8, #min(x$timeseries$ssb[1]/x$refpts[1,"k"],1),
              step=0),
      lt=list(low  =0.1, #rev(x$timeseries$ssb)[1]/x$refpts[1,"k"]*0.5,
              up   =0.8, #rev(x$timeseries$ssb)[1]/x$refpts[1,"k"]*2.0,
              refyr=max(x$year)),sigv=0,
      k=list(dist="unif",low=k*.1,up=k*10,mean=0,sd=0),
      r=list(dist="unif",low=r*.2,up=r*2,mean=0,sd=0),
      M=list(dist="unif",low=0.2,up=0.2,mean=0.00,sd=0.00),
      nsims=30000,
      graphs=NULL)

  fit})

save(cmsy10,file="/home/laurence-kell/Desktop/papers/data-poor/results/ssCMSY10Results.RData")
```

```{r}
load("/home/laurence-kell/Desktop/papers/data-poor/results/ssBDResults.RData")  
load("/home/laurence-kell/Desktop/papers/data-poor/results/ssBD4Results.RData")  
load("/home/laurence-kell/Desktop/papers/data-poor/results/ssSRAResults.RData")
load("/home/laurence-kell/Desktop/papers/data-poor/results/ssSRPResults.RData")
load("/home/laurence-kell/Desktop/papers/data-poor/results/ssCMSYResults.RData")

bd=ldply(bd,function(x){
  if (is.null(x)) rQeturn(NULL)
  subset(x$results,variable%in%c("b_div_bmsy","b"))})

bd4=ldply(bd4,function(x){
  if (is.null(x)) return(NULL)
  subset(x$results,variable%in%c("b_div_bmsy","b"))})

sra=ldply(sra,function(x){
  if (is.null(x)) return(NULL)
  subset(x$results,variable%in%c("b_div_bmsy","b"))})

srp=ldply(srap,function(x){
  if (is.null(x)) return(NULL)
  subset(x$results,variable%in%c("b_div_bmsy","b"))})

cmsy.bmsy=ldply(cmsy,function(x){
  dt=cbind(x$timeseries,bmsy=rep(x$Values$Bmsy,rep=length(unique(x$timeseries$year))))
  ddply(dt, .(flag,year), with, quantile(value/bmsy,probs=c(0.975,0.945,0.5,0.045,0.025)))
  })
names(cmsy.bmsy)[c(5:7)]=c("upper","mean","lower")

cmsy.b=ldply(cmsy,function(x){
  dt=cbind(x$timeseries,bmsy=rep(x$Values$Bmsy,rep=length(unique(x$timeseries$year))))
  ddply(dt, .(flag,year), with, quantile(value,probs=c(0.975,0.945,0.5,0.045,0.025)))
  })
names(cmsy.b)[c(5:7)]=c("upper","mean","lower")

dat=rbind.fill(cbind(Model="Catch & Index",        bd),
               cbind(Model="Catch & Index Error",  bd4),
               cbind(Model="Catch & Heuristics",   sra),
               cbind(Model="Catch & Priors",       srp),
               cbind(Model="CMSY",           subset(cmsy.b,   flag==1),variable="b"),
               cbind(Model="CMSY",           subset(cmsy.bmsy,flag==1),variable="b_div_bmsy"))[c(1:4,6:8)]

save(dat,file="/home/laurence-kell/Desktop/papers/data-poor/results/ssAll.RData")
```


```{r}
ssdat=merge(ss,rfpts)

ggplot(  subset(dat,variable=="b"))+ 
  geom_ribbon(aes(year,ymax=upper,ymin=lower),fill="red",alpha=0.25)+
  geom_line(aes(year,mean))+
  geom_line(aes(year,ssb),data=ssdat)+
  facet_grid(stk~Model,scale="free")+
  xlab("Biomass")+ylab("Year")+
  scale_x_continuous(breaks=seq(0,60,10))+
  theme_bw()
```

**Figure `r iFig=iFig+1; iFig`** Absolute trends 


```{r}
ggplot(  subset(dat,variable=="b"&Model=="Catch & Index"))+ 
  geom_ribbon(aes(year,ymax=upper,ymin=lower),fill="red",alpha=0.25)+
  geom_line(aes(year,mean))+
  geom_line(aes(year,ssb),data=ssdat)+
  facet_grid(stk~Model,scale="free")+
  xlab("Biomass")+ylab("Year")+
  scale_x_continuous(breaks=seq(0,60,10))+
  theme_bw()
```

**Figure `r iFig=iFig+1; iFig`** Absolute trends: catch & index


```{r}
ggplot( subset(dat,variable=="b"&Model=="Catch & Heuristics"))+ 
  geom_ribbon(aes(year,ymax=upper,ymin=lower),fill="red",alpha=0.25)+
  geom_line(aes(year,mean))+
  geom_line(aes(year,ssb),data=ssdat)+
  facet_grid(stk~Model,scale="free")+
  xlab("Biomass")+ylab("Year")+
  scale_x_continuous(breaks=seq(0,60,10))+
  theme_bw()
```

**Figure `r iFig=iFig+1; iFig`** Absolute trends: catch 


```{r}
ggplot( subset(dat,variable=="b"&Model=="Catch & Priors"))+ 
  geom_ribbon(aes(year,ymax=upper,ymin=lower),fill="red",alpha=0.25)+
  geom_line(aes(year,mean))+
  geom_line(aes(year,ssb),data=ssdat)+
  facet_grid(stk~Model,scale="free")+
  xlab("Biomass")+ylab("Year")+
  scale_x_continuous(breaks=seq(0,60,10))+
  theme_bw()
```

**Figure `r iFig=iFig+1; iFig`** Absolute trends: catch & priors


```{r}
ggplot( subset(dat,variable=="b"&Model=="CMSY"))+ 
  geom_ribbon(aes(year,ymax=upper,ymin=lower),fill="red",alpha=0.25)+
  geom_line(aes(year,mean))+
  geom_line(aes(year,ssb),data=ssdat)+
  facet_grid(stk~Model,scale="free")+
  xlab("Biomass")+ylab("Year")+
  scale_x_continuous(breaks=seq(0,60,10))+
  theme_bw()
```

**Figure `r iFig=iFig+1; iFig`** Absolute trends: CMSY 

```{r}
ggplot( subset(dat,variable=="b_div_bmsy"))+ 
  geom_hline(aes(yintercept=1))+
  geom_ribbon(aes(year,ymax=upper,ymin=lower),fill="red",alpha=0.25)+
  geom_line(aes(year,mean),col="red")+
  geom_line(aes(year,ssb/ssbmsy),data=ssdat)+
  xlab(expression(B:B[MSY]))+ylab("Year")+
  facet_grid(stk~Model,scale="free")
```

**Figure `r iFig=iFig+1; iFig`** Trends relative to $B/B_{MSY}$ 


```{r}
load("/home/laurence-kell/Desktop/papers/data-poor/results/ssBD10Results.RData")  
load("/home/laurence-kell/Desktop/papers/data-poor/results/ssBD410Results.RData")  
load("/home/laurence-kell/Desktop/papers/data-poor/results/ssSRA10Results.RData")
load("/home/laurence-kell/Desktop/papers/data-poor/results/ssSRP10Results.RData")
load("/home/laurence-kell/Desktop/papers/data-poor/results/ssCMSY10Results.RData")

bd=ldply(bd10,function(x){
  if (is.null(x)) return(NULL)
  subset(x$results,variable%in%c("b_div_bmsy","b"))})

bd4=ldply(bd410,function(x){
  if (is.null(x)) return(NULL)
  subset(x$results,variable%in%c("b_div_bmsy","b"))})

sra=ldply(sra10,function(x){
  if (is.null(x)) return(NULL)
  subset(x$results,variable%in%c("b_div_bmsy","b"))})

srp=ldply(srap10,function(x){
  if (is.null(x)) return(NULL)
  subset(x$results,variable%in%c("b_div_bmsy","b"))})

cmsy.bmsy=ldply(cmsy10,function(x){
  dt=cbind(x$timeseries,bmsy=rep(x$Values$Bmsy,rep=length(unique(x$timeseries$year))))
  ddply(dt, .(flag,year), with, quantile(value/bmsy,probs=c(0.975,0.945,0.5,0.045,0.025)))
  })
names(cmsy.bmsy)[c(5:7)]=c("upper","mean","lower")

cmsy.b=ldply(cmsy10,function(x){
  dt=cbind(x$timeseries,bmsy=rep(x$Values$Bmsy,rep=length(unique(x$timeseries$year))))
  ddply(dt, .(flag,year), with, quantile(value,probs=c(0.975,0.945,0.5,0.045,0.025)))
  })
names(cmsy.b)[c(5:7)]=c("upper","mean","lower")

dat=rbind.fill(cbind(Model="Catch & Index",        bd),
               cbind(Model="Catch & Index Error",  bd4),
               cbind(Model="Catch & Heuristics",   sra),
               cbind(Model="Catch & Priors",       srp),
               cbind(Model="CMSY",             subset(cmsy.b,   flag==1),variable="b"),
               cbind(Model="CMSY",             subset(cmsy.b,   flag==1),variable="b"))[c(1:4,6:8)]


save(dat,file="/home/laurence-kell/Desktop/papers/data-poor/results/ss10.RData")
```


```{r}
ggplot( subset(dat,variable=="b_div_bmsy"))+  
  geom_hline(aes(yintercept=1))+
  geom_ribbon(aes(year,ymax=upper,ymin=lower),fill="red",alpha=0.25)+
  geom_line(aes(year,mean),col="red")+
  geom_line(aes(year,ssb/ssbmsy),data=ssdat)+
  xlab(expression(B:B[MSY]))+ylab("Year")+
  facet_grid(stk~Model,scale="free")
```

**Figure `r iFig=iFig+1; iFig`** Trends relative to $B/B_{MSY}$ 



```{r}
twothree<-function(x,n1=2,n2=3){
  
  if (length(x)<n1+n2) return(NULL)
  
  mean(x[length(x)-seq(n1)+1])/mean(x[length(x)-(n1+n2):n2+1])}

trend<-function(x,n=10){
    
    if (length(x)<n) return(NA)
    
    y=x[length(x)-(n:1)+1]
    y=y/mean(y)
    
    if (any(is.na(x))) return(NA)
    
    lm(y~x,data=data.frame(x=seq(n),y=y))$coef[2]}
```


```{r}
load("/home/laurence-kell/Desktop/papers/data-poor/data/om.RData")
load("/home/laurence-kell/Desktop/papers/data-poor/results/jb10.RData")
res<-cbind("Yrs"="10",dat)
load("/home/laurence-kell/Desktop/papers/data-poor/results/jbAll.RData")
res<-rbind(res,cbind("Yrs"="All",dat))
```

```{r}
dt=rbind.fill(cbind(Model="OM",subset(om,OM=="SS")[,c("stk","biomass")]),
              transform(subset(dat,variable=="b")[,c("stk","Model","mean","lower","upper")],biomass=mean))[,-4]

tab=ddply(subset(dt,!is.na(biomass)), .(stk,Model), with, rbind(c(variable="t23",value=twothree(biomass,5)),
                                                                c(variable="t5", value=trend(   biomass,5))))

cast(tab,variable+Model~stk)
```
